openapi: 3.0.4
info:
  title: Product API
  description: Simple API for managing products based on the OpenAPI 3.0 specification
  version: 1.0.0

servers:
  - url: http://localhost:5000

paths:
  /:
    get:
      summary: Returns '<h1>Hello world</h1>'
      responses:
        "200":
          description: Returns '<h1>Hello world</h1>'
          content: 
            text/html:
              schema:
                type: string
                example: "<h1>Hello world</h1>"

  /api/v1/products:
    get:
      summary: Returns list of all products
      description: Returns list of all products
      tags:
        - Products
      responses:
        "200":
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductResponse"
    post:
      summary: Creates a new product
      tags:
        - Products
      requestBody:
        description: Parameters for new product
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreateRequest"
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "400":
          description: Missing required fields
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Resource already existed
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/products/{id}:
    parameters:
      - name: id
        in: path
        description: Product's id
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Getting product by id
      tags:
        - Products
      responses:
        "200":
          description: Product found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "404":
          description: Product not found
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      summary: Edit a product using id
      tags:
        - Products
      requestBody:
        description: Describe product to be edited
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreateRequest"
      responses:
        "200":
          description: Product edited successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "400":
          description: Missing required fields
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Product not found
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Edit a product using id
      tags:
        - Products
      requestBody:
        description: Describe product to be edited
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductPatchRequest"
      responses:
        "200":
          description: Product edited successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"
        "400":
          description: Missing required fields
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: Product not found
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete product using id
      tags:
        - Products
      responses:
        "204":
          description: Deleted successfully
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          description: Product's id, autoincrement
          example: 1
        name:
          type: string
          description: Product's name
          example: Dell precision 5540 laptop
        description: 
          type: string
          description: Product's description
          example: Dell workstation, i7 9th generation
        price:
          type: number
          description: Product's price
          example: 999.99
        sku: 
          type: string
          description: Product's sku
          example: LP-XYZ-001
        quantity:
          type: integer
          description: Product's quantity
          example: 100
        created_at:
          type: integer
          description: When the product was added to database
          example: 102983902181
        updated_at:
          type: integer
          description: When the product was last modified
          example: 102983902183

    ProductCreateRequest:
      type: object
      properties:
        name:
          type: string
          description: Product's name
          example: Dell precision 5540 laptop
        description: 
          type: string
          description: Product's description
          example: Dell workstation, i7 9th generation
        price:
          type: number
          description: Product's price
          example: 999.99
        sku: 
          type: string
          description: Product's sku
          example: LP-XYZ-001
        quantity:
          type: integer
          description: Product's quantity
          example: 100
      required:
        - name
        - price
        - quantity

    ProductPatchRequest:
      type: object
      properties:
        name:
          type: string
          description: Product's name
          example: Dell precision 5540 laptop
        description: 
          type: string
          description: Product's description
          example: Dell workstation, i7 9th generation
        price:
          type: number
          description: Product's price
          example: 999.99
        sku: 
          type: string
          description: Product's sku
          example: LP-XYZ-001
        quantity:
          type: integer
          description: Product's quantity
          example: 100

    Error:
      type: object
      properties:
        error:
          type: string
          description: String representation of the error that occurred
          example: Product's price is missing
